### ISSUE TITLE
layer1 configuration phase is failing with the mentioned error

### ISSUE THREAD

**Issue by selldinesh** [open-traffic-generator/snappi-convergence#6] opened 2021-06-28 07:53 UTC
imports = [{'ieeeL1Defaults': False, 'xpath': '/vport[1]/l1Config/novusHundredGigLan'}]

    def _set_gigabit_auto_negotiation(self, vport, layer1, imports):
        advertise = []
        advertise.append(Vport._SPEED_MAP[
                 layer1.get('speed', with_default=True)])
        auto_field_name  = 'enableAutoNegotiation'
        if re.search('novustengiglan', vport['type'].lower()) is not None:
            auto_field_name = 'autoNegotiate'
        # Due to ieeeL1Defaults dependency
        ieee_media_defaults = {
            'xpath':
                vport['xpath'] + '/l1Config/' + vport['type'].replace('Fcoe', ''),
            'ieeeL1Defaults':
                layer1.get('ieee_media_defaults', with_default=True)
        }
        self._add_l1config_import(vport, ieee_media_defaults, imports)
        auto_negotiate = layer1.get('auto_negotiate', with_default=True)
>       rs_fec = auto_negotiate.get('rs_fec', with_default=True)
E       AttributeError: 'bool' object has no attribute 'get'

**Comment by ANISH-GOTTAPU** [comment] 2021-06-28 15:51
The issue is fixed with `snappi[ixnetwork]==0.4.14`q

**Closed** 2021-07-01 06:24 UTC
